export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_ITINERARY_DATA = 'LOAD_ITINERARY_DATA';
export const CREATE_ITINERARY_DATA = 'CREATE_ITINERARY_DATA';
export const DELETE_ITINERARY_DATA = 'DELETE_ITINERARY_DATA';
export const UPDATE_ITINERARY_DATA = 'UPDATE_ITINERARY_DATA';

export const LOAD_MESSAGES_DATA = 'LOAD_MESSAGES_DATA';
export const CREATE_MESSAGES_DATA = 'CREATE_MESSAGES_DATA';

export const LOAD_COMMENTS_DATA = 'LOAD_COMMENTS_DATA';
export const CREATE_COMMENTS_DATA = 'CREATE_COMMENTS_DATA';

export const LOAD_LOCATION_DATA = 'LOAD_LOCATION_DATA';
export const LOAD_MAP_DATA = 'LOAD_MAP_DATA';
export const UPVOTE_LOCATION = 'UPVOTE_LOCATION';